use role SYSADMIN;
create or replace database INFA_METRICS;
--drop database INFA_METRICS;
create or replace stage INFA_METRICS_STAGE directory = (enable = true) encryption = (type = 'snowflake_sse');

use role ACCOUNTADMIN;
create or replace role INFORMATICA_METRICS_ANALYST;
grant role INFORMATICA_METRICS_ANALYST to user PatrickGarner;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE INFORMATICA_METRICS_ANALYST;
GRANT USAGE ON DATABASE INFA_METRICS TO ROLE INFORMATICA_METRICS_ANALYST;
GRANT USAGE ON SCHEMA INFA_METRICS.PUBLIC TO ROLE INFORMATICA_METRICS_ANALYST;
GRANT CREATE TABLE ON SCHEMA INFA_METRICS.PUBLIC TO ROLE INFORMATICA_METRICS_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA INFA_METRICS.PUBLIC TO ROLE INFORMATICA_METRICS_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA INFA_METRICS.PUBLIC TO ROLE INFORMATICA_METRICS_ANALYST;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE INFA_METRICS TO ROLE INFORMATICA_METRICS_ANALYST;
GRANT TRUNCATE ON ALL TABLES IN SCHEMA INFA_METRICS.PUBLIC TO ROLE INFORMATICA_METRICS_ANALYST;
GRANT CREATE VIEW ON SCHEMA INFA_METRICS.PUBLIC TO ROLE INFORMATICA_METRICS_ANALYST;
GRANT CREATE PROCEDURE ON SCHEMA INFA_METRICS.PUBLIC TO ROLE INFORMATICA_METRICS_ANALYST;
-- Regarding internal stages:
--   1. READ permission must come before WRITE
--   2. Also, operating on a stage also requires the USAGE privilege on the parent database and schema
--   See https://docs.snowflake.com/en/user-guide/security-access-control-privileges.html#stage-privileges
grant READ on stage INFA_METRICS_STAGE to role INFORMATICA_METRICS_ANALYST;
grant WRITE on stage INFA_METRICS_STAGE to role INFORMATICA_METRICS_ANALYST;

use role INFORMATICA_METRICS_ANALYST;
use database INFA_METRICS;
use schema INFA_METRICS.PUBLIC;
